Removed cloudant and logging. Also added test to scripts
watson-developer-cloud/car-dashboard pull request #42
Opened 2016-12-01 00:03 UTC by stevenpkg

Removed conversation logging as not required now

2016-12-01 02:42 UTC, germanattanasio requested changes

2016-12-01 02:42 UTC, germanattanasio commented on package.json
> +    "nano" : "*"
nano is not required

2016-12-01 02:42 UTC, germanattanasio commented on package.json
> +    "nano" : "*"
And if it is, never use *

2016-12-01 02:42 UTC, germanattanasio commented on test/test.express.js
> +app.use(bodyParser.json());
`app.js` already adds the json parser

2016-12-01 03:01 UTC, stevenpkg commented
Have made the changes you requested

2016-12-01 16:23 UTC, germanattanasio commented
@stevenpkg the changes look good. I still think there are unused dependencies like `express-csv`
If you install `depcheck` with: 
```
npm install depcheck -g
```

Then you can run
```
depcheck
```

And see the unused dependencies.

2016-12-01 23:13 UTC, stevenpkg commented
Thanks for letting me know about depcheck. Cleaned up the following dependencies:
Unused dependencies
* chai
* request
* watson-speech
Unused devDependencies
* gulp-fontmin
* gulp-if
* gulp-imagemin
* gulp-postcss
* gulp-preprocess
* gulp-uglify
* nock
* uglifyjs
* whatwg-fetch
Missing dependencies
* eve

2016-12-01 23:57 UTC, stevenpkg commented
I see mocha is in both dependencies, is this correct?

},
  "author": "IBM Corp.",
  "dependencies": {
    "body-parser": "1.15.1",
    "compression": "1.6.2",
    "dotenv": "^2.0.0",
    "express": "4.13.4",
    "mocha": "^2.5.3",
    "vcap_services": "^0.2.0",
    "watson-developer-cloud": "^1.12.2",
    "express-csv": "0.6.0"
  },
  "devDependencies": {
    "babel-eslint": "^6.0.4",
    "eslint": "^2.8.0",
    "eslint-config-airbnb-es5": "^1.0.9",
    "eslint-plugin-react": "^5.1.1",
    "gulp": "^3.9.1",
    "istanbul": "^0.4.2",
    "gulp-clean-css": "2.0.7",
    "gulp-develop-server": "^0.5.1",
    "gulp-load-plugins": "^0.7.1",
    "gulp-size": "^1.1.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-useref": "^3.0.8",
    "mocha": "^2.4.5",
    "supertest": "^1.2.0",
    "eve": "^0.3.1"
  }

2016-12-08 11:23 UTC, AthifAlpha01 commented
Deployed but there is an error saying " The service may be down at the moment; please check here for the current status.
If the service is OK, the app may not be configured correctly, please check workspace id and credentials for typos.
If the service is running and the app is configured correctly, try refreshing the page and/or trying a different request."
How can I overcome this ?

2016-12-19 22:42 UTC, merged