Added IAM API key support
watson-developer-cloud/car-dashboard pull request #92
Opened 2018-07-22 22:57 UTC by stevenpkg

2018-07-22 23:25 UTC, germanattanasio requested changes

2018-07-22 23:25 UTC, germanattanasio commented on README.md
> +1. Download and install the [Cloudfoundry CLI](https://github.com/cloudfoundry/cli) tool.
Check the README from https://github.com/watson-developer-cloud/assistant-simple/blob/master/README.md we don't use `cf` anymore. We use the IBM Cloud CLI now

2018-07-22 23:25 UTC, germanattanasio commented on package.json
> +    "watson-developer-cloud": "^3.5.1",
3.7.0

2018-07-22 23:25 UTC, germanattanasio commented on routes/conversation.js
> +var assistant;
If we instruct them to use IAM and the `.env` file then the constructor can be

```js
assistant = new AssistantV1({
  version: '2018-02-16',
});
```

2018-07-23 14:24 UTC, germanattanasio requested changes

2018-07-23 14:24 UTC, germanattanasio commented on routes/conversation.js
>  if (process.env.ASSISTANT_IAM_APIKEY !== undefined && process.env.ASSISTANT_IAM_APIKEY.length > 0) {
After doing this for all the demos, I realized that we could simplify this doing

```

const assistant = new AssistantV1({
  version: '2018-02-16',
});
```

The SDK is already looking at the Environment variables, so we don't need to do anything else. I tested it, and it works.

2018-07-26 00:44 UTC, stevenpkg commented
German can you approve this?

2018-07-26 16:33 UTC, germanattanasio approved these changes

2018-07-26 16:34 UTC, merged